export const userData = [
  {
    name: "Jan",
    "Active Users": 4000,
  },
  {
    name: "Feb",
    "Active Users": 3000,
  },
  {
    name: "Mar",
    "Active Users": 2000,
  },
  {
    name: "Apr",
    "Active Users": 2780,
  },
  {
    name: "May",
    "Active Users": 1890,
  },
  {
    name: "Jun",
    "Active Users": 2390,
  },
  {
    name: "Jul",
    "Active Users": 3490,
  },
  {
    name: "Aug",
    "Active Users": 3800,
  },
  {
    name: "Sep",
    "Active Users": 2500,
  },
  {
    name: "Oct",
    "Active Users": 4800,
  },
  {
    name: "Nov",
    "Active Users": 2181,
  },
  {
    name: "Dec",
    "Active Users": 3908,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 6500,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 2,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 3,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Inactive",
    transaction: "UGX 763,000",
  },
  {
    id: 4,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 554,000",
  },
  {
    id: 5,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 321,000",
  },
  {
    id: 6,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 7,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 8,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 9,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
  {
    id: 10,
    username: "Ojok Simon Peter",
    avatar: "images/Ojok.jpg",
    email: "simonpeter.oj@gmail.com",
    status: "Active",
    transaction: "UGX 489,000",
  },
];

export const productRows = [
  {
    id: 1,
    productName: "Apple",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 300,
    status: "Available",
    price: "UGX 4,000",
  },
  {
    id: 2,
    productName: "Gifts",
    productImage: "images/gifts.jpg",
    productCategory: "Gifts",
    stock: 432,
    status: "Available",
    price: "UGX 1,489,000",
  },
  {
    id: 3,
    productName: "Coca Cola",
    productImage: "images/cocacola.jpg",
    productCategory: "Soft Drinks",
    stock: 0,
    status: "Out of stock",
    price: "UGX 48,000",
  },
  {
    id: 4,
    productName: "Apple",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 678,
    status: "Avaialble",
    price: "UGX 35,000",
  },
  {
    id: 5,
    productName: "Apple",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 145,
    status: "Available",
    price: "UGX 8,000",
  },
  {
    id: 6,
    productName: "Apple",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 145,
    status: "Available",
    price: "UGX 6,000",
  },
  {
    id: 7,
    productName: "Coca Cola",
    productImage: "images/cocacola.jpg",
    productCategory: "Soft drinks",
    stock: 432,
    status: "Available",
    price: "UGX 1,489,000",
  },
  {
    id: 8,
    productName: "Gift",
    productImage: "images/gifts.jpg",
    productCategory: "Gifts",
    stock: 0,
    status: "Out of stock",
    price: "UGX 48,000",
  },
  {
    id: 9,
    productName: "Apple",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 678,
    status: "Avaialble",
    price: "UGX 35,000",
  },
  {
    id: 10,
    productName: "Ice Cream",
    productImage: "images/apple.jpg",
    productCategory: "Fruits",
    stock: 145,
    status: "Available",
    price: "UGX 28,000",
  },
];
